CREATE TABLE [dbo].[GeneralSettings] (
    [GeneralSettId]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [CountryId]                  BIGINT        NULL,
    [PhoneId]                    BIGINT        NULL,
    [CompanyName]                VARCHAR (100) NULL,
    [CompanyLogo]                VARCHAR (100) NULL,
    [CompanyEmail]               VARCHAR (100) NULL,
    [CompanyReference]           VARCHAR (100) NULL,
    [CompanyPIN]                 VARCHAR (100) NULL,
    [ClientApiEndpoint]          VARCHAR (200) NULL,
    [CurrencyId]                 BIGINT        NULL,
    [IndividualMultipleAccounts] BIT           NULL,
    [CCEmail]                    VARCHAR (50)  NULL,
    [IsCCEmail]                  BIT           NOT NULL,
    [EmailCustomerAutomatically] BIT           NOT NULL,
    [TimeZone]                   VARCHAR (150) NULL,
    [TimeZoneOffSet]             VARCHAR (50)  NULL,
    [StaffAutoLogOff]            BIT           NOT NULL,
    [ApplyTax]                   BIT           NOT NULL,
    [noOfDecimalPlaces]          BIGINT        NULL,
    [IsEmailEnabled]             BIT           NOT NULL,
    [IsSmsEnabled]               BIT           NOT NULL,
    [IsTemplateTrancated]        BIT           NOT NULL,
    [Hascard]         INT           NOT NULL DEFAULT 0,
    [Extra]         VARCHAR(100)           NULL ,
    [Extra1]         VARCHAR(100)           NULL ,
    [Extra2]         VARCHAR(100)           NULL ,
    [Extra3]         VARCHAR(100)           NULL ,
    [Extra4]         VARCHAR(100)           NULL ,
    [Extra5]         VARCHAR(100)           NULL ,
    [Createdby]                  BIGINT        NULL,
    [Modifiedby]                 BIGINT        NULL,
    [DateCreated]                DATETIME      NULL,
    [DateModified]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GeneralSettId] ASC),
    FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[SystemCurrencies] ([CurrencyId]),
    FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[SystemCurrencies] ([CurrencyId])
);



