CREATE TABLE [dbo].[Systemstaffs] (
    [StaffId]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [Firstname]          VARCHAR (100) NULL,
    [Lastname]           VARCHAR (100) NULL,
    [Emailaddress]       VARCHAR (100) NOT NULL,
    [Username]           VARCHAR (100) NOT NULL,
    [Roleid]             BIGINT        NOT NULL,
    [Phoneid]            BIGINT        NOT NULL,
    [Phonenumber]        VARCHAR (12)  NOT NULL,
    [Dob]                VARCHAR (50)  NULL,
    [Gender]             VARCHAR (15)  NULL,
    [IDNumber]           VARCHAR (15)  NULL,
    [Passwords]          VARCHAR (100) NULL,
    [passwordharsh]      VARCHAR (100) NULL,
    [CountryId]          BIGINT        NOT NULL,
    [RegionId]           BIGINT        NOT NULL,
    [RegionAreaId]       BIGINT        NOT NULL,
    [IsActive]           BIT           DEFAULT ((1)) NOT NULL,
    [IsDeleted]          BIT           DEFAULT ((0)) NOT NULL,
    [IsDefault]          BIT           DEFAULT ((0)) NOT NULL,
    [Isstaff]            BIT           DEFAULT ((0)) NOT NULL,
    [Isshop]            BIT           DEFAULT ((0)) NOT NULL,
    [Iscustomer]            BIT           DEFAULT ((0)) NOT NULL,
    [Changepassword]     BIT           DEFAULT ((0)) NOT NULL,
    [Passwordchangedate] DATETIME      NULL,
    [Extra]              VARCHAR (100) NULL,
    [Extra1]             VARCHAR (100) NULL,
    [Extra2]             VARCHAR (100) NULL,
    [Extra3]             VARCHAR (100) NULL,
    [Extra4]             VARCHAR (100) NULL,
    [Extra5]             VARCHAR (100) NULL,
    [Extra6]             VARCHAR (100) NULL,
    [Extra7]             VARCHAR (100) NULL,
    [Extra8]             VARCHAR (100) NULL,
    [Extra9]             VARCHAR (100) NULL,
    [ModuleId]           BIGINT        DEFAULT ((0)) NOT NULL,
    [ParentId]           BIGINT        DEFAULT ((0)) NOT NULL,
    [LoginStatus]        INT           DEFAULT ((0)) NOT NULL,
    [Createdby]          BIGINT        NULL,
    [Modifiedby]         BIGINT        NULL,
    [Datecreated]        DATETIME      NULL,
    [Datemodified]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([StaffId] ASC),
    FOREIGN KEY ([CountryId]) REFERENCES [dbo].[SystemCountry] ([CountryId]),
    FOREIGN KEY ([CountryId]) REFERENCES [dbo].[SystemPhoneCodes] ([Phoneid]),
    FOREIGN KEY ([CountryId]) REFERENCES [dbo].[SystemCountry] ([CountryId]),
    FOREIGN KEY ([CountryId]) REFERENCES [dbo].[SystemPhoneCodes] ([Phoneid]),
    FOREIGN KEY ([RegionAreaId]) REFERENCES [dbo].[SystemCountryRegionsAreas] ([RegionAreaId]),
    FOREIGN KEY ([RegionAreaId]) REFERENCES [dbo].[SystemCountryRegionsAreas] ([RegionAreaId]),
    FOREIGN KEY ([RegionId]) REFERENCES [dbo].[SystemCountryRegions] ([RegionId]),
    FOREIGN KEY ([RegionId]) REFERENCES [dbo].[SystemCountryRegions] ([RegionId]),
    FOREIGN KEY ([Roleid]) REFERENCES [dbo].[Systemroles] ([Roleid]),
    FOREIGN KEY ([Roleid]) REFERENCES [dbo].[Systemroles] ([Roleid]),
    UNIQUE NONCLUSTERED ([Phonenumber] ASC),
    UNIQUE NONCLUSTERED ([Username] ASC)
);



