CREATE TABLE [dbo].[AutomationSalesData] (
    [AutomationSaleId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [TenantId]         BIGINT          NOT NULL,
    [StationId]        BIGINT          NOT NULL,
    [EfdId]            VARCHAR (50)    NULL,
    [RegId]            VARCHAR (50)    NULL,
    [FdcNum]           BIGINT          NULL,
    [FdcName]          VARCHAR (50)    NULL,
    [RdgSaveNum]       BIGINT          NULL,
    [FdcSaveNum]       BIGINT          NULL,
    [RdgDate]          DATETIME        NOT NULL,
    [RdgTime]          VARCHAR (50)    NULL,
    [FdcDate]          DATETIME        NOT NULL,
    [FdcTime]          VARCHAR (50)    NULL,
    [RdgIndex]         BIGINT          NULL,
    [RdgId]            BIGINT          NULL,
    [Fp]               BIGINT          NULL,
    [PumpAddr]         BIGINT          NULL,
    [Noz]              BIGINT          NULL,
    [Price]            DECIMAL (18, 2) NULL,
    [Vol]              DECIMAL (18, 2) NULL,
    [Amo]              DECIMAL (18, 2) NULL,
    [VolTotal]         DECIMAL (18, 2) NULL,
    [RoundType]        BIGINT          NULL,
    [RdgProd]          BIGINT          NULL,
    [FdcProd]          BIGINT          NULL,
    [FdcProdName]      VARCHAR (50)    NULL,
    [FdcTank]          VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([AutomationSaleId] ASC)
);

