CREATE TABLE [dbo].[Tenantaccounts] (
    [Tenantid]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [Tenantlogo]          VARCHAR (400)  NULL,
    [Tenantname]          VARCHAR (70)  NOT NULL,
    [Tenantkey]           VARCHAR (70)  NOT NULL,
    [Tenantkrapin]        VARCHAR (70)  NOT NULL,
    [Emailaddress]        VARCHAR (100) NOT NULL,
    [Connectionstring]    VARCHAR (200) NOT NULL,
    [Tenantsubdomain]     VARCHAR (70)  NOT NULL,
    [Tenantemailkey]      VARCHAR (70)  NULL,
    [Tenantemailpassword] VARCHAR (70)  NULL,
    [Tenantmessageusername] VARCHAR (70)  NULL,
    [Tenantmessageapikey] VARCHAR (70)  NULL,
    [Extra]               VARCHAR (100) NULL,
    [Extra1]              VARCHAR (100) NULL,
    [Extra2]              VARCHAR (100) NULL,
    [Extra3]              VARCHAR (100) NULL,
    [Extra4]              VARCHAR (100) NULL,
    [Extra5]              VARCHAR (100) NULL,
    [Extra6]              VARCHAR (100) NULL,
    [Extra7]              VARCHAR (100) NULL,
    [Extra8]              VARCHAR (100) NULL,
    [Extra9]              VARCHAR (100) NULL,
    [Extra10]             VARCHAR (100) NULL,
    [Tenantloginstatus] BIGINT NOT  NULL DEFAULT 0,
    [Isactive]            BIT           DEFAULT ((1)) NOT NULL,
    [Isdeleted]           BIT           DEFAULT ((0)) NOT NULL,
    [Datecreated]         DATETIME      DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([Tenantid] ASC),
    UNIQUE NONCLUSTERED ([Emailaddress] ASC),
    UNIQUE NONCLUSTERED ([Tenantkey] ASC),
    UNIQUE NONCLUSTERED ([Tenantkrapin] ASC),
    UNIQUE NONCLUSTERED ([Tenantname] ASC),
    UNIQUE NONCLUSTERED ([Tenantsubdomain] ASC)
);

