CREATE TABLE [dbo].[Systemstaffs] (
    [StaffId]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [Tenantid]           BIGINT        NOT NULL,
    [Firstname]          VARCHAR (100) NULL,
    [Lastname]           VARCHAR (100) NULL,
    [Emailaddress]       VARCHAR (100) NOT NULL,
    [Roleid]             BIGINT        NOT NULL,
    [Phoneid]            BIGINT        NOT NULL,
    [Phonenumber]        VARCHAR (12)  NOT NULL,
    [Dob]                DATETIME      NULL,
    [Gender]             VARCHAR (15)  NULL,
    [IDNumber]           VARCHAR (15)  NULL,
    [Passwords]          VARCHAR (100) NULL,
    [Passwordharsh]      VARCHAR (100) NULL,
    [IsActive]           BIT           DEFAULT ((1)) NOT NULL,
    [IsDeleted]          BIT           DEFAULT ((0)) NOT NULL,
    [IsDefault]          BIT           DEFAULT ((0)) NOT NULL,
    [Isstaff]            BIT           DEFAULT ((0)) NOT NULL,
    [Changepassword]     BIT           DEFAULT ((0)) NOT NULL,
    [Passwordchangedate] DATETIME      NULL,
    [Extra]              VARCHAR (100) NULL,
    [Extra1]             VARCHAR (100) NULL,
    [Extra2]             VARCHAR (100) NULL,
    [Extra3]             VARCHAR (100) NULL,
    [Extra4]             VARCHAR (100) NULL,
    [Extra5]             VARCHAR (100) NULL,
    [Extra6]             VARCHAR (100) NULL,
    [Extra7]             VARCHAR (100) NULL,
    [Extra8]             VARCHAR (100) NULL,
    [Extra9]             VARCHAR (100) NULL,
    [ParentId]           BIGINT        DEFAULT ((0)) NOT NULL,
    [LoginStatus]        INT           DEFAULT ((0)) NOT NULL,
    [Createdby]          BIGINT        NULL,
    [Modifiedby]         BIGINT        NULL,
    [Datecreated]        DATETIME      NULL,
    [Datemodified]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([StaffId] ASC),
    FOREIGN KEY ([Phoneid]) REFERENCES [dbo].[Systemphonecodes] ([Phoneid]),
    FOREIGN KEY ([Phoneid]) REFERENCES [dbo].[Systemphonecodes] ([Phoneid]),
    FOREIGN KEY ([Roleid]) REFERENCES [dbo].[Systemroles] ([Roleid]),
    FOREIGN KEY ([Tenantid]) REFERENCES [dbo].[Systemtenants] ([Tenantid]),
    FOREIGN KEY ([Tenantid]) REFERENCES [dbo].[Systemtenants] ([Tenantid]),
    UNIQUE NONCLUSTERED ([Emailaddress] ASC),
    UNIQUE NONCLUSTERED ([Phonenumber] ASC)
);

