CREATE TABLE [dbo].[Systemtenants] (
    [Tenantid]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [Tenantname]      VARCHAR (70)   NOT NULL,
    [Tenantlogo]      VARCHAR (200)  NULL,
    [Emailserver]     VARCHAR (200)  DEFAULT ('info@uttambsolutions.com') NOT NULL,
    [Emailpassword]   VARCHAR (200)  DEFAULT ('K@ribun1') NOT NULL,
    [Consumerkey]     VARCHAR (200)  NOT NULL,
    [Shortcode]       VARCHAR (200)  NOT NULL,
    [Consumersecret]  VARCHAR (200)  NOT NULL,
    [Tenantstatus]    INT            DEFAULT ((0)) NOT NULL,
    [Passkey]         NVARCHAR (700) NOT NULL,
    [Validationurl]   VARCHAR (200)  NULL,
    [Confirmationurl] VARCHAR (200)  NULL,
    [Sandboxregurl]   VARCHAR (200)  NULL,
    [Sandboxsimurl]   VARCHAR (200)  NULL,
    [Sandboxauthurl]  VARCHAR (200)  NULL,
    [Systemurl]       VARCHAR (200)  NULL,
    [Stkpushurl]      VARCHAR (200)  NULL,
    [Extra]           VARCHAR (100)  NULL,
    [Extra1]          VARCHAR (100)  NULL,
    [Extra2]          VARCHAR (100)  NULL,
    [Extra3]          VARCHAR (100)  NULL,
    [Extra4]          VARCHAR (100)  NULL,
    [Extra5]          VARCHAR (100)  NULL,
    [Extra6]          VARCHAR (100)  NULL,
    [Extra7]          VARCHAR (100)  NULL,
    [Extra8]          VARCHAR (100)  NULL,
    [Extra9]          VARCHAR (100)  NULL,
    [Extra10]         VARCHAR (100)  NULL,
    [Isactive]        BIT            DEFAULT ((1)) NOT NULL,
    [Isdeleted]       BIT            DEFAULT ((0)) NOT NULL,
    [Createdby]       BIGINT         NOT NULL,
    [Modifiedby]      BIGINT         NOT NULL,
    [Datemodified]    DATETIME       NOT NULL,
    [Datecreated]     DATETIME       NOT NULL,
    PRIMARY KEY CLUSTERED ([Tenantid] ASC)
);



