CREATE TABLE [dbo].[Systemassetdetail] (
    [Assetdetailid]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [Customerid]        BIGINT          NOT NULL,
    [Assetid]           BIGINT          NOT NULL,
    [Assetnumber]       VARCHAR (100)   NOT NULL,
    [Assetmakeid]       BIGINT          DEFAULT ((0)) NOT NULL,
    [Assetmodelid]      BIGINT          DEFAULT ((0)) NOT NULL,
    [Assetchasenumber]  VARCHAR (100)   NULL,
    [Yearofmanufacture] INT             NOT NULL,
    [Tankcapacity]      DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [Odometerreading]   DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [Extra]             VARCHAR (100)   NULL,
    [Extra1]            VARCHAR (100)   NULL,
    [Extra2]            VARCHAR (100)   NULL,
    [Extra3]            VARCHAR (100)   NULL,
    [Extra4]            VARCHAR (100)   NULL,
    [Extra5]            VARCHAR (100)   NULL,
    [Extra6]            VARCHAR (100)   NULL,
    [Extra7]            VARCHAR (100)   NULL,
    [Extra8]            VARCHAR (100)   NULL,
    [Extra9]            VARCHAR (100)   NULL,
    [Extra10]           VARCHAR (100)   NULL,
    [Isactive]          BIT             DEFAULT ((1)) NOT NULL,
    [Isdeleted]         BIT             DEFAULT ((0)) NOT NULL,
    [Createdby]         BIGINT          NOT NULL,
    [Modifiedby]        BIGINT          NOT NULL,
    [Datemodified]      DATETIME        NOT NULL,
    [Datecreated]       DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([Assetdetailid] ASC),
    FOREIGN KEY ([Assetid]) REFERENCES [dbo].[Systemassets] ([Assetid]),
    FOREIGN KEY ([Customerid]) REFERENCES [dbo].[Systemcustomers] ([Customerid])
);

