CREATE TABLE [dbo].[Systemloandetail] (
    [Loandetailid]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [Customerid]    BIGINT          NOT NULL,
    [Assetdetailid] BIGINT          NOT NULL,
    [Loanamount]    DECIMAL (18, 2) NOT NULL,
    [Paidamount]    DECIMAL (18, 2) NOT NULL,
    [Interestrate]  DECIMAL (18, 2) NOT NULL,
    [Loanperiod]    DECIMAL (18, 2) NOT NULL,
    [Paymentterm]   VARCHAR (100)   NOT NULL,
    [Startdate]     DATETIME        DEFAULT (getdate()) NOT NULL,
    [Laonstatus]    INT             DEFAULT ((3)) NOT NULL,
    [Extra]         VARCHAR (100)   NULL,
    [Extra1]        VARCHAR (100)   NULL,
    [Extra2]        VARCHAR (100)   NULL,
    [Extra3]        VARCHAR (100)   NULL,
    [Extra4]        VARCHAR (100)   NULL,
    [Extra5]        VARCHAR (100)   NULL,
    [Extra6]        VARCHAR (100)   NULL,
    [Extra7]        VARCHAR (100)   NULL,
    [Extra8]        VARCHAR (100)   NULL,
    [Extra9]        VARCHAR (100)   NULL,
    [Extra10]       VARCHAR (100)   NULL,
    [Isactive]      BIT             DEFAULT ((1)) NOT NULL,
    [Isdeleted]     BIT             DEFAULT ((0)) NOT NULL,
    [Createdby]     BIGINT          NOT NULL,
    [Modifiedby]    BIGINT          NOT NULL,
    [Datemodified]  DATETIME        NOT NULL,
    [Datecreated]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([Loandetailid] ASC),
    FOREIGN KEY ([Assetdetailid]) REFERENCES [dbo].[Systemassetdetail] ([Assetdetailid]),
    FOREIGN KEY ([Customerid]) REFERENCES [dbo].[Systemcustomers] ([Customerid])
);

