CREATE TABLE [dbo].[Systemcustomers] (
    [Customerid]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [Tenantid]       BIGINT        NOT NULL,
    [Firstname]      VARCHAR (100) NOT NULL,
    [Lastname]       VARCHAR (100) NOT NULL,
    [Imageurl]       VARCHAR (200) NULL,
    [Customeremail]  VARCHAR (100) NOT NULL,
    [Phoneid]        BIGINT        NOT NULL,
    [Phonenumber]    VARCHAR (12)  NOT NULL,
    [Customerstatus] INT           DEFAULT ((0)) NOT NULL,
    [Idnumber]       VARCHAR (100) NOT NULL,
    [Krapin]         VARCHAR (100) NOT NULL,
    [Licensenumber]  VARCHAR (100) NOT NULL,
    [Gender]         INT           DEFAULT ((0)) NOT NULL,
    [Extra]          VARCHAR (100) NULL,
    [Extra1]         VARCHAR (100) NULL,
    [Extra2]         VARCHAR (100) NULL,
    [Extra3]         VARCHAR (100) NULL,
    [Extra4]         VARCHAR (100) NULL,
    [Extra5]         VARCHAR (100) NULL,
    [Extra6]         VARCHAR (100) NULL,
    [Extra7]         VARCHAR (100) NULL,
    [Extra8]         VARCHAR (100) NULL,
    [Extra9]         VARCHAR (100) NULL,
    [Extra10]        VARCHAR (100) NULL,
    [Isactive]       BIT           DEFAULT ((1)) NOT NULL,
    [Isdeleted]      BIT           DEFAULT ((0)) NOT NULL,
    [Createdby]      BIGINT        NOT NULL,
    [Modifiedby]     BIGINT        NOT NULL,
    [Datemodified]   DATETIME      NOT NULL,
    [Datecreated]    DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([Customerid] ASC),
    UNIQUE NONCLUSTERED ([Customeremail] ASC),
    UNIQUE NONCLUSTERED ([Idnumber] ASC),
    UNIQUE NONCLUSTERED ([Krapin] ASC),
    UNIQUE NONCLUSTERED ([Licensenumber] ASC)
);

